version: "3.7"

services:
  runner:
    image: runner3:v0.0.2
    container_name: runner-self-hosted
    privileged: true
    environment:
      RUNNER_NAME: "my-runner"
      RUNNER_REPOSITORY_URL: ${RUNNER_REPOSITORY_URL}
      #RUNNER_ORGANIZATION_URL: ${RUNNER_ORGANIZATION_URL}
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sockz
