name: Main
## Workflow for enviroments
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Esta línea permite accionar el workflow manualmente desde GitHub Actions, muy útil para testear correrlo incluso en otras ramas
  workflow_dispatch:

env:
# Comando para leer la Versión del Firmware actualizada en el repositorio
  VERSION: $(awk '/#define FIRMWARE_VERSION/ {print $NF}' ./include/param.hpp)

jobs:
  build-upload-prd:
    name: Build-Upload
    runs-on: self-hosted   
    environment: main
    steps: 
      - uses: actions/checkout@v3
      - name: "Set firmware version"
        run: |
          echo "VERSION=${{ env.VERSION }}"
      - name: "Build firmware"
        run: |
          pio run --environment nodemcu-32s-${{ vars.ENV }} 
      - name: "Set new version to update server"
        run: |
          echo "Set URL Firmware ${{ vars.UPDATE_JSON_URL}}"
          cp .pio/build/nodemcu-32s-${{ vars.ENV }}/firmware.bin /home/runner/${{ vars.PATH_ENV }}/firmware/update/firmware-${{ env.VERSION }}.bin
          echo "Firmware.bin compilado y copiado a /home/runner/${{ vars.PATH_ENV }}/firmware/update"
          cp /home/runner/${{ vars.PATH_ENV }}/firmware/update/update.json update.json
          jq --argjson version_arg ${{ env.VERSION }} '.version |= $version_arg | .version |= tonumber' update.json > tmp && mv tmp update.json
          cp update.json /home/runner/${{ vars.PATH_ENV }}/firmware/update/update.json
          echo "update.json actualizado con la ultima version: ${{ env.VERSION }}"
